practice/urls.py
from debug_toolbar import urls
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="practice")),
    path("__debug__/", include("debug_toolbar.urls")),
]

todo/urls.py
from django.urls import path

from todo.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    toggle_assign_to_task,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("<int:pk>/assign/", toggle_assign_to_task, name="assign"),
    path("create/", TaskCreateView.as_view(), name="task-create"),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "practice"

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now=True)
    deadline = models.DateTimeField(blank=True, null=True)
    completed = models.BooleanField(default=False)
    tags = models.ManyToManyField(to=Tag, related_name="tags")

    class Meta:
        ordering = ("completed", "-created")

todo/forms.py
import datetime

from django import forms

from todo.models import Tag, Task


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    deadline = forms.DateTimeField(
        input_formats="%Y-%m-%d %H:%M", required=False, initial=datetime.datetime.today
    )

    class Meta:
        model = Task
        fields = ("content", "deadline", "tags")

todo/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from todo.forms import TaskForm
from todo.models import Task, Tag


# Create your views here.


class TaskListView(generic.ListView):
    model = Task
    context_object_name = "task_list"
    queryset = Task.objects.all()


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("practice:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("practice:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("practice:task-list")


class TagListView(generic.ListView):
    model = Tag
    queryset = Tag.objects.all()


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("practice:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("practice:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("practice:tag-list")


def toggle_assign_to_task(request, pk):
    task = Task.objects.get(id=pk)
    if task.completed:
        task.completed = False
    else:
        task.completed = True
    task.save()
    return HttpResponseRedirect(reverse_lazy("practice:task-list"))

templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
        rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
        crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <title>ToDo List</title>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}
        </div>
        <div class="col-sm-10 ">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>


</body>
</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item h4"><a href="{% url 'practice:task-list' %}">Home</a></li>
  <li class="list-group-item h4"><a href="{% url 'practice:tag-list' %}">Tags</a></li>
</ul>

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag.</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Tags
    <a href="{% url 'practice:tag-create' %}" class="btn btn-primary link-to-page float-end">
      Add
    </a>
  </h1>

  {% if tag_list %}
    <table class="table h4">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
              {{ tag.name }}
          </td>
          <td>
              <a class="btn btn-secondary" href="{% url 'practice:tag-update' pk=tag.id %}">
                Update
              </a>
            </td>
            <td>
              <a class="btn btn-secondary"
                href="{% url 'practice:tag-delete' pk=tag.id %}">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
      <p>There are no tags.</p>
  {% endif %}
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task.</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/task_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    TODO list
    <a class="btn btn-primary float-end" href="{% url 'practice:task-create' %}">Add task</a>
  </h1>


  {% if task_list %}
    <table class="table">
      {% for task in task_list %}
        <tr>
        <td>
          <p class="h4">
            <strong>
              {{ task.content }}
              {% if task.completed %}
                <span style="color: green">Done</span>
              {% else %}
                <span style="color: red">Not done</span>
              {% endif %}
              {% if task.completed %}
                <a class="btn btn-secondary float-end" href="{% url 'practice:assign' pk=task.id%}">Undo</a>
              {% else %}
                <a class="btn btn-success float-end" href="{% url 'practice:assign' pk=task.id%}">Complete</a>
              {% endif %}
            </strong>
          </p>
            <p class="h6 d-inline">Created: {{ task.created }}</p>
            {% if task.deadline %}
              <p style="color: saddlebrown" class="h6 d-inline">Deadline: {{ task.deadline }}</p>
            {% endif %}
            <p class="text-secondary h4">
              Tags:
              {% for tag in task.tags.all %}
                {{ tag }}
              {% endfor %}
            <a href="{% url 'practice:task-update' pk=task.id %}">Update</a>
            <a href="{% url 'practice:task-delete' pk=task.id%}">Delete</a>
            </p>
        </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
    <p>No task</p>
  {% endif %}

{% endblock %}